// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcoM7hqNA7-3NivM_Nghu-aqNTCUIWpFo',
    appId: '1:497818130166:web:7187cd8b3774f963a37ed7',
    messagingSenderId: '497818130166',
    projectId: 'player-portfolio-45a0e',
    authDomain: 'player-portfolio-45a0e.firebaseapp.com',
    storageBucket: 'player-portfolio-45a0e.firebasestorage.app',
    measurementId: 'G-CQKZJ11P4P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhkrUlCHafdJY71oMzS5UixFE6AI9XfJ0',
    appId: '1:497818130166:android:dae62e62e94a265da37ed7',
    messagingSenderId: '497818130166',
    projectId: 'player-portfolio-45a0e',
    storageBucket: 'player-portfolio-45a0e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_2FrhqopVHFdP6LWvZEegjcCsJORkuxk',
    appId: '1:497818130166:ios:790158343427e8b7a37ed7',
    messagingSenderId: '497818130166',
    projectId: 'player-portfolio-45a0e',
    storageBucket: 'player-portfolio-45a0e.firebasestorage.app',
    iosClientId: '497818130166-g8qbog73nvjh19jm96f1kcfb0ielrqkp.apps.googleusercontent.com',
    iosBundleId: 'com.example.easyQurbani',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_2FrhqopVHFdP6LWvZEegjcCsJORkuxk',
    appId: '1:497818130166:ios:790158343427e8b7a37ed7',
    messagingSenderId: '497818130166',
    projectId: 'player-portfolio-45a0e',
    storageBucket: 'player-portfolio-45a0e.firebasestorage.app',
    iosClientId: '497818130166-g8qbog73nvjh19jm96f1kcfb0ielrqkp.apps.googleusercontent.com',
    iosBundleId: 'com.example.easyQurbani',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcoM7hqNA7-3NivM_Nghu-aqNTCUIWpFo',
    appId: '1:497818130166:web:7d2d435bd2db62eda37ed7',
    messagingSenderId: '497818130166',
    projectId: 'player-portfolio-45a0e',
    authDomain: 'player-portfolio-45a0e.firebaseapp.com',
    storageBucket: 'player-portfolio-45a0e.firebasestorage.app',
    measurementId: 'G-4QZ371KKFB',
  );
}
